# Generated by Django 3.0.7 on 2020-08-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifier',
            name='category',
            field=models.CharField(max_length=20),
        ),
    ]
